pages/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name='[pages]'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mgspot/', views.mgspot, name='mgspot'),
    path('addspot/', views.addspot, name='addspot'),
    path('delspot/<spot_id>', views.delspot, name='delspot'),
    path('editspot/<spot_id>', views.editspot, name='editspot'),
    path('mgplace/', views.mgplace, name='mgplace'),
    path('addplace/', views.addplace, name='addplace'),
    path('delplace/<place_id>', views.delplace, name='delplace'),
    path('editplace/<place_id>', views.editplace, name='editplace'),
    path('placedetail/<place_id>', views.placedetail, name='placedetail'),
    path('spotdetail/<spot_id>', views.spotdetail, name='spotdetail'),
    path('mguser/', views.mguser, name='mguser'),
    path('deluser/<user_id>', views.deluser, name='deluser'),
    path('myinfo/', views.myinfo, name='myinfo'),
    path('editmyinfo/', views.editmyinfo, name='editmyinfo'),
    path('home/', views.home, name='home'),
    path('searchplace/', views.searchplace, name='searchplace'),
    path('highsearch/', views.highsearch, name='highsearch'),
    path('retiregroup/', views.retiregroup, name='retiregroup'),
    path('toshareplace/<place_id>', views.toshareplace, name='toshareplace'),
    path('shareplace/<place_id>', views.shareplace, name='shareplace'),
    path('likeplace/<place_id>', views.likeplace, name='likeplace'),
    path('localspot/<place_id>', views.localspot, name='localspot'),
    path('searchspot/', views.searchspot, name='searchspot'),
    path('mginfo_c/', views.mginfo_c, name='mginfo_c'),
    path('editinfo_c/<place_id>', views.editinfo_c, name='editinfo_c'),
    path('magorder_c/', views.mgorder_c, name='mgorder_c'),
    path('makeorder/<place_id><room_kind>', views.makeorder, name='makeorder'),
    path('cancelorder/<order_id>', views.cancelorder, name='cancelorder'),
    path('confirmorder/<order_id>', views.confirmorder, name='confirmorder'),
    path('refuseorder/<order_id>', views.refuseorder, name='refuseorder'),
    path('finishorder/<order_id>', views.finishorder, name='finishorder'),
]

retirementPlaceSys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls', namespace='pages')),
    url(r'^media/(?P<path>.*)', serve, {"document_root":MEDIA_ROOT}),
]

pages/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    usertype = models.IntegerField(default=0)#0-个人会员，1-管理员，2-养老机构
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.EmailField()
    phone=models.CharField(max_length=50,default='')
    address=models.CharField(max_length=200,default='')

class Places(models.Model):
    user = models.OneToOneField(Users, on_delete=models.CASCADE,null=True)#user 主键标志对应的会员账户，一对一关系
    name = models.CharField(max_length=100,default=u'未命名')
    phone=models.CharField(max_length=50,default='')#热线电话
    keywords = models.CharField(max_length=300,default='')
    introduce = models.TextField(max_length=2000,default='')
    cost = models.IntegerField(default=0)#费用
    traffic = models.CharField(max_length=100,default=u'高铁')#交通方式,高铁，航空，港口，可多选
    price = models.CharField(max_length=50,default=u'中')#物价，高，中，低  单选
    spotticket=models.CharField(max_length=50,default=u'贵')#景点门票，贵，较贵，便宜，较便宜 单选
    hospital=models.CharField(max_length=50,default=u'有三甲医院') #有三甲医院，无三甲医院，单选
    address = models.CharField(max_length=300)
    singleroomcount= models.IntegerField(default=20)#单人间个数
    singleroomfee= models.IntegerField(default=0)#单人间费用
    doubleroomcount= models.IntegerField(default=20)#双人间个数
    doubleroomfee= models.IntegerField(default=0)#双人间费用
    familyroomcount= models.IntegerField(default=20)#家庭间个数
    familyroomfee= models.IntegerField(default=0)#家庭间费用
    image = models.ImageField(upload_to='images',default="upimg/default.jpg") 
    likedcount=models.IntegerField(default=0)#点赞个数
    sharedcount=models.IntegerField(default=0)#被分享次数
    publishtime = models.DateTimeField('date published')

class Scenicspot(models.Model):
    name = models.CharField(max_length=100)
    introduce = models.TextField(max_length=2000)
    address = models.CharField(max_length=300)
    image = models.ImageField(upload_to='images')
    opentime = models.CharField(max_length=100)
    nearbyplace=models.ManyToManyField(Places)
    
class Shares(models.Model):
    user = models.ForeignKey(Users,on_delete=models.CASCADE)#user 外键标志谁分享的
    place = models.ForeignKey(Places,on_delete=models.CASCADE)#place 外键,分享的是哪个地点
    text = models.CharField(max_length=500)#分享时写的内容
    time = models.DateTimeField('date published')#分享时间
    image = models.ImageField(upload_to='images',default='')

class Order(models.Model):
    user = models.ForeignKey(Users,on_delete=models.CASCADE)#user
    place = models.ForeignKey(Places,on_delete=models.CASCADE)#place 下单到哪个养老机构，一对一
    roomkind= models.IntegerField(default=0)#房间类型 0-单人间，1-双人间，2-家庭间
    roomcount= models.IntegerField(default=0)#房间个数
    guestname = models.TextField(max_length=50)#入住人名字
    phone=models.CharField(max_length=50,default='')#入住人电话
    guestcount= models.IntegerField(default=1)#入住人数
    checkintime = models.DateField(auto_now=False, auto_now_add=True)#入住时间
    checkouttime = models.DateField(auto_now=False, auto_now_add=True)#离开时间
    fee=models.IntegerField(default=0)#费用
    state=models.IntegerField(default=0)#订单状态，0-待商家确认，1-已确认，2-已取消，3-已拒绝，4-已完成
    time = models.DateTimeField('date published')#订单创建日期

class Comment(models.Model):
    user = models.ForeignKey(Users,on_delete=models.CASCADE)#user 外键标志谁评论的
    place = models.ForeignKey(Places,on_delete=models.CASCADE)#place 外键评论的那个养老机构
    text = models.CharField(max_length=500)#评论的内容
    time = models.DateTimeField('date published')#评论时间

class Like(models.Model):
    user = models.ForeignKey(Users,on_delete=models.CASCADE)#user 外键标志谁点赞的
    place = models.ForeignKey(Places,on_delete=models.CASCADE)#place 点赞的那个养老机构
    time = models.DateTimeField('date published')#评论时间

templates/pages/highsearch.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block style %}
<style>
    #link{
        font-size:20px;
        padding: 6px;
        text-decoration:none;
        color:gray;          
    }
    #selectedlink{
        font-size:20px;
        padding: 6px;
        text-decoration:none;
        color:black;         
    }
    #textcontent {
        width: 80%;
        height: auto;
        word-wrap:break-word;
        word-break:break-all;
        overflow: hidden;
        margin:5% auto
    }
</style>
{% endblock %}
{% block topmenucenter %}
    <div style="padding:20px">
        <a id =link_center href="{% url 'pages:home' %}">首页</a>
		<a id =selectedlink_center href="{% url 'pages:highsearch' %}">高级筛选</a>
        <a id =link_center  href="{% url 'pages:searchspot' %}">搜索景点</a> 
		<a id =link_center  href="{% url 'pages:retiregroup' %}">养老圈</a> 
    </div>
{% endblock %}

{% block contentbody %}
    <div style="margin: 10% 20%;">
        <form enctype='multipart/form-data' action="{% url 'pages:highsearch' %}" method="post" name='highsearch' >{% csrf_token %}
            <table>
                <tr>
                    <td></td>
                    <td><input type="submit" name='highsearch' value="高级筛选" style="width:100%; height:40px;float:right"></td>
                </tr>
                <tr>
                    <td style="width:20%">关键词：</td>
                    <td style="width:80%"><input type="text" id="id_name" name="keywords" placeholder="请输入关键词，比如诗歌之下乡，临海等" style="width:100%; height:60px"  /></td>
                </tr>
                <tr>
                    <td>费用：</td>
                    <td><input type="text" id="id_name" name="cost" placeholder="请输入价格(元/月）" style="width:100%; height:60px" /></td>
                </tr>
                <tr>
                    <td style="width:20%">交通：</td>
                    <td style="width:80%">
                        <label><input name="traffic" type="checkbox" value="高铁" />高铁 </label> 
                        <label><input name="traffic" type="checkbox" value="航空" />航空 </label> 
                        <label><input name="traffic" type="checkbox" value="港口" />港口 </label> 
                    </td>
                </tr>  
                <tr>
                    <td style="width:20%">物价：</td>
                    <td style="width:80%">
                        <label><input name="price" type="radio""  value="高" />高 </label> 
                        <label><input name="price" type="radio"" value="中" />中 </label> 
                        <label><input name="price" type="radio"" value="低" />低 </label> 
                    </td>
                </tr>
                <tr>
                    <td style="width:20%">景点门票：</td>
                    <td style="width:80%">
                        <label><input name="spotticket" type="radio"" value="贵" />贵 </label> 
                        <label><input name="spotticket" type="radio"" value="较贵" />较贵 </label> 
                        <label><input name="spotticket" type="radio"" value="便宜" />便宜 </label> 
                        <label><input name="spotticket" type="radio"" value="较便宜" />较便宜 </label> 
                    </td>
                </tr>
                <tr>
                    <td style="width:20%">医疗：</td>
                    <td style="width:80%">
                        <label><input name="hospital" type="radio"" value="有三甲医院" />有三甲医院 </label> 
                        <label><input name="hospital" type="radio"" value="无三甲医院" />无三甲医院 </label> 
                    </td>
                </tr>
            </table>
        </form>
        <div id=textcontent>
            {% for place in place_list.all %}
                <h4>{{ place.name }}</h4>
            <img src='{{ MEDIA_URL }}{{ place.image}}' width="800" height="600" alt=''/>
                <p align="left" id=pcontent><lable>关键词:</label> {{ place.keywords}}</p>
                <p align="left" id=pcontent><lable>简介:</label> {{ place.introduce}}</p>
            <p align="left" id=pcontent>电话：{{place.phone}} </p>
            <p align="left" id=pcontent>地址：{{place.address}}</p>
                <p align="left" id=pcontent>
                    <tr>
                    <td>平均费用：{{place.cost}}(元/月)</td>
                    <td>&nbsp&nbsp交通:</td>
                    <td></td>{{ place.traffic}}</td>
                    </tr>
                </p>
                <p align="left" id=pcontent>
                    <tr>
                        <td>物价:</td>
                    	<td>{{place.price}}</td>
                    	<td>&nbsp&nbsp景点门票:</td>
                    	<td>{{place.spotticket}}</td>
                    	<td>&nbsp&nbsp医疗:</td>
                    	<td>{{place.hospital}}</td>
                    </tr>
                </p>
                <p align="left" id=pcontent>
                    <tr>
                        <td >附近景点：</td>
                        <td>
                            {% for spot in place.scenicspot_set.all %}
                            &nbsp&nbsp<a  href="{% url 'pages:spotdetail' spot.id %}">{{ spot.name}}</a>
                            {% endfor %}
                        </td>
                    </tr>
                </p>
            <p align="left" id=pcontent>
                <tr>
                    <td>单人房：</td>
                    <td>&nbsp&nbsp{{place.singleroomcount}}间</td>
                    <td>&nbsp&nbsp{{place.singleroomfee}}元/天</td>
                    <td>&nbsp&nbsp<a href="{% url 'pages:makeorder' place.id 0 %}">预定</a></td>
                </tr>
            </p>
            <p align="left" id=pcontent>
                <tr>
                    <td>双人房：</td>
                    <td>&nbsp&nbsp{{place.doubleroomcount}}间</td>
                    <td>&nbsp&nbsp{{place.doubleroomfee}}元/天</td>
                    <td>&nbsp&nbsp<a href="{% url 'pages:makeorder' place.id 1 %}">预定</a></td>
                </tr>
            </p>
            <p align="left" id=pcontent>
                <tr>
                    <td>家庭房：</td>
                    <td>&nbsp&nbsp{{place.familyroomcount}}间</td>
                    <td>&nbsp&nbsp{{place.familyroomfee}}元/天</td>
                    <td>&nbsp&nbsp<a href="{% url 'pages:makeorder' place.id 2 %}">预定</a></td>
                </tr>
            </p>
            <p align="left" style="font-size:20px;color:grey">
                <td></td><lable id=''>更新时间:</lable> {{place.publishtime}}</td>
                <td>&nbsp&nbsp<a href="{% url 'pages:likeplace' place.id %}"><input type="submit" id =good value='' style="background:url('/static/images/good.png') no-repeat;width:36px; height:36px;"></lable></a>&nbsp&nbsp{{place.likedcount}}</td>
                <td>&nbsp&nbsp<a href="{% url 'pages:toshareplace' place.id %}">分享</a>&nbsp&nbsp{{place.sharedcount}}</td>
            </p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/pages/mgspot.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block style %}
<style>
    #textcontent {
        width: 80%;
        height: auto;
        word-wrap:break-word;
        word-break:break-all;
        overflow: hidden;
        margin:5% auto
    }
</style>
{% endblock %}

{% block topmenucenter %}
    <div style="padding:20px">
        <a id =link_center href="{% url 'pages:home' %}">首页</a> 
        <a id =selectedlink_center href="{% url 'pages:mgspot' %}">景点管理</a> 
        <a id =link_center  href="{% url 'pages:mguser' %}">个人会员管理</a> 
		<a id =link_center href="{% url 'pages:mgplace' %}">养老机构管理</a>
    </div>
{% endblock %}

{% block contentbody %}
    <div style="margin: 5% 5%;">
        <div id=textcontent>
                <a href="{% url 'pages:addspot' %}"><input type="submit" value="添加景点" style="width:120px; height:30px;float:right" ></a>
            {% for spot in spot_list.all %}
                <h4>{{ spot.name }}</h4>
                <img name="image" src='{{ MEDIA_URL }}{{ spot.image}}' alt=''/ width="800" height="600">
                <p align="left" ><lable>简介:</label> {{ spot.introduce}}</p>
                <p align="left" id=pcontent><lable>附近养老机构:</label>
                    {% for place in spot.nearbyplace.all %}
                    &nbsp&nbsp<a  href="{% url 'pages:placedetail' place.id %}">{{ place.name}}</a>
                    {% endfor %}
                </p>
                <p align="left" id=pcontent><lable>详细地址:</label> {{ spot.address}}</p>
                <p align="left" id=pcontent><lable>开放时间:</label> {{ spot.opentime}}</p>
                <p align="center">
                    <tr>
                        <td><a href="{% url 'pages:editspot' spot.id %}">编辑</a></td>
                        <td><a href="{% url 'pages:delspot' spot.id %}">删除</a></td>  
                    </tr>
                </p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/pages/my_c.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block style %}
<style>
    #textcontent {
        width: 80%;
        height: auto;
        word-wrap:break-word;
        word-break:break-all;
        overflow: hidden;
        margin:5% auto
    }
    #pcontent{
        font-size:28px;
        color:darkslategrey
    }
</style>
{% endblock %}
{% block topmenucenter %}
    <div style="padding:20px">
        <a id =link_center href="{% url 'pages:home' %}">首页</a>
		<a id =link_center href="{% url 'pages:highsearch' %}">高级筛选</a>
        <a id =link_center  href="{% url 'pages:searchspot' %}">搜索景点</a> 
		<a id =link_center  href="{% url 'pages:retiregroup' %}">养老圈</a>
        <a id =link_center href="{% url 'pages:mginfo_c' %}">商家信息管理</a> 
    </div>
{% endblock %}

{% block contentbody %}
    <div style="margin: 0% 10% 0% 10%">
        <div style="width:100%; height:300px">
            <h4>我的->个人信息</h4>
            <table style="margin:0% 0% 0% 0%;width:100%">
                <tr align="left">
                    <td width="50%">账户:{{ my.name }}</td>
                    <td width="50%">邮箱:{{ my.email}}</td>
                </tr>
            </table>
            <p align="left">
                地址:{{ my.address }}
                <br/>
                电话:{{ my.phone }}
                <br/>
                <a  href="{% url 'pages:editmyinfo' %}">编辑</a>
            </p>
        </div>
        <div style="margin: 0% 10% 0% 10%;width:100%; height:300px; color:darkslategrey;font-size:28px;">
            <h4>我的->订单</h4>
            {% for order in order_list.all %}
            <table align="left" style="margin:0% 0% 0% 0%;width:100%" >
                <tr>
                    <td style="width:50%" align="left">养老机构：{{order.place.name}}</td>
                    <td style="width:50%" align="left">电话：{{order.place.phone}}</td>
                </tr>
                <tr>
                    <td style="width:50%" align="left">入住人姓名：{{order.guestname}}</td>
                    <td style="width:50%"  align="left">电话：{{order.phone}}</td>
                </tr>
                <tr>
                    <td style="width:50%" align="left">{{order.checkintime}}入住</td>
                    <td style="width:50%" align="left">{{order.checkouttime}}离开</td>
                </tr>
                <tr>
                    <td tyle="width:50%" align="left">费用：{{order.fee}}</td>
                    <td style="width:50%"  align="left">订单状态：<label name="state" id= "state{{order.state}}"></label></td>
                </tr>
            </table>
            <p align="left">
                地址：{{order.place.address}}<br>
                <b align="left"  style="color:grey;font-size:20px;"> 订单创建时间：{{order.time}}</b>
                <a align="right"  name="confirm" href="{% url 'pages:confirmorder' order.id %}">确认</a>
                <a align="right"  name="refuse" href="{% url 'pages:refuseorder' order.id %}">拒绝</a>
                <a align="right"  name="finish" href="{% url 'pages:finishorder' order.id %}">完成</a>
            </p>
            {% endfor %}
        </div>
        <script>
            window.onload=function(){
            var confirms = document.getElementsByName('confirm');
            var refuses = document.getElementsByName('refuse');
            var finishs = document.getElementsByName('finish');
            var states = document.getElementsByName('state');
            for( var i=0; i<states.length; i++){
                var state=states[i];
                if(state.id.indexOf("0")!=-1){
                    state.innerText="已提交待商家确认";
                    confirms[i].style.display="display";
                    refuses[i].style.display="display";
                    finishs[i].style.display="none";
                }
                else if(state.id.indexOf("1")!=-1){
                    state.innerText="已确认";
                    confirms[i].style.display="none";
                    refuses[i].style.display="none";
                    finishs[i].style.display="display";
                }
                else if(state.id.indexOf("2")!=-1){
                    state.innerText="已取消";
                    confirms[i].style.display="none";
                    refuses[i].style.display="none";
                    finishs[i].style.display="none";
                }
                else if(state.id.indexOf("3")!=-1){
                    state.innerText="已拒绝";
                    confirms[i].style.display="none";
                    refuses[i].style.display="none";
                    finishs[i].style.display="none";
                }
                else if(state.id.indexOf("4")!=-1){
                    state.innerText="已完成";
                    confirms[i].style.display="none";
                    refuses[i].style.display="none";
                    finishs[i].style.display="none";
                }
            }
        }
        </script>
    </div>
{% endblock %}

templates/pages/place_addspot.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block style %}
<style>
    #link{
        font-size:20px;
        padding: 6px;
        text-decoration:none;
        color:gray;          
    }
    #selectedlink{
        font-size:20px;
        padding: 6px;
        text-decoration:none;
        color:black;         
    }
</style>
{% endblock %}

{% block topmenucenter %}
    <div style="padding:20px">
        <a id =link_center href="{% url 'pages:home' %}">首页</a>
		<a id =link_center href="{% url 'pages:highsearch' %}">高级筛选</a>
        <a id =link_center  href="{% url 'pages:searchspot' %}">搜索景点</a> 
		<a id =link_center  href="{% url 'pages:retiregroup' %}">养老圈</a>
        <a id =selectedlink_center href="{% url 'pages:mginfo_c' %}">商家信息管理</a> 
    </div>
{% endblock %}

{% block contentbody %}
    <form enctype='multipart/form-data' action="{% url 'pages:addspot' %}" method="post" name='addspot' >{% csrf_token %}
        <table width="90%"  align="center">
             <tr>
                 <td>名称:</td>
                 <td><input type="text" id="id_name" name="name" placeholder="请输入名称" style="width:100%; height:60px" autofocus required  /></td>
             </tr>
             <tr>
                <td>详细地址:</td>
                <td><textarea id="id_address" placeholder="请输入地址" name="address"   style="width:100%; height:80px"></textarea></td>
             </tr>
             <tr>
                    <td>时间:</td>
                    <td><input type="text" placeholder="请输入开放时间" name="time"   style="width:100%;height:60px"></td>
            </tr>
             <tr>
                 <td>简介:</td>
                 <td><textarea id="id_introduce" placeholder="请输入简介" name="introduce"   style="width:100%; height:300px"></textarea></td>
             </tr>
             <tr>
                <td>图片:</td>
                <td><input type="file" id="id_image" name="image" placeholder="上传图片" style="width:100%; height:32px"></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="确认添加" style="width:120px; height:30px;float:right" ></td>
            </tr>
        </table>     
    </form>
{% endblock %}

templates/pages/placedetail.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block style %}
<style>
    #link{
        font-size:20px;
        padding: 6px;
        text-decoration:none;
        color:gray;          
    }
    #selectedlink{
        font-size:20px;
        padding: 6px;
        text-decoration:none;
        color:black;         
    }
    #textcontent {
        width: 80%;
        height: auto;
        word-wrap:break-word;
        word-break:break-all;
        overflow: hidden;
        margin:5% auto
    }
</style>
{% endblock %}
{% block topmenucenter %}
    <div style="padding:20px">
        <a id =link_center href="{% url 'pages:home' %}">首页</a>
        <a id =link_center href="{% url 'pages:highsearch' %}">高级筛选</a>
        <a id =link_center  href="{% url 'pages:searchspot' %}">搜索景点</a> 
		<a id =link_center  href="{% url 'pages:retiregroup' %}">养老圈</a> 
    </div>
{% endblock %}

{% block contentbody %}
    <div style="text-align:center;margin: 10% 10% 10% 10%" >
        <h4>{{ place.name }}</h4>
            <img src='{{ MEDIA_URL }}{{ place.image}}' width="800" height="600" alt=''/>
            <p align="left" id=pcontent><lable>关键词:</label> {{ place.keywords}}</p>
            <p align="left" id=pcontent><lable>简介:</label> {{ place.introduce}}</p>
            <p align="left" id=pcontent>电话：{{place.phone}} </p>
            <p align="left" id=pcontent>地址：{{place.address}}</p>
            <p align="left" id=pcontent>
                <tr>
                    <td>平均费用：{{place.cost}}(元/月)</td>
                    <td>&nbsp&nbsp交通:</td>
                    <td></td>{{ place.traffic}}</td>
                    </tr>
                </p>
                <p align="left" id=pcontent>
                    <tr>
                        <td>物价:</td>
                    	<td>{{place.price}}</td>
                    	<td>&nbsp&nbsp景点门票:</td>
                    	<td>{{place.spotticket}}</td>
                    	<td>&nbsp&nbsp医疗:</td>
                    	<td>{{place.hospital}}</td>
                    </tr>
                </p>
                <p align="left" id=pcontent>
                    <tr>
                        <td >附近景点：</td>
                        <td>
                            {% for spot in place.scenicspot_set.all %}
                            &nbsp&nbsp<a  href="{% url 'pages:spotdetail' spot.id %}">{{ spot.name}}</a>
                            {% endfor %}
                        </td>
                    </tr>
                </p>
            <p align="left" id=pcontent>
                <tr>
                    <td>单人房：</td>
                    <td>&nbsp&nbsp{{place.singleroomcount}}间</td>
                    <td>&nbsp&nbsp{{place.singleroomfee}}元/天</td>
                    <td>&nbsp&nbsp<a href="{% url 'pages:makeorder' place.id 0 %}">预定</a></td>
                </tr>
            </p>
            <p align="left" id=pcontent>
                <tr>
                    <td>双人房：</td>
                    <td>&nbsp&nbsp{{place.doubleroomcount}}间</td>
                    <td>&nbsp&nbsp{{place.doubleroomfee}}元/天</td>
                    <td>&nbsp&nbsp<a href="{% url 'pages:makeorder' place.id 1 %}">预定</a></td>
                </tr>
            </p>
            <p align="left" id=pcontent>
                <tr>
                    <td>家庭房：</td>
                    <td>&nbsp&nbsp{{place.familyroomcount}}间</td>
                    <td>&nbsp&nbsp{{place.familyroomfee}}元/天</td>
                    <td>&nbsp&nbsp<a href="{% url 'pages:makeorder' place.id 2 %}">预定</a></td>
                </tr>
            </p>
            <p align="left" style="font-size:20px;color:grey">
                <td></td><lable id=''>更新时间:</lable> {{place.publishtime}}</td>
                <td>&nbsp&nbsp<a href="{% url 'pages:likeplace' place.id %}"><input type="submit" id =good value='' style="background:url('/static/images/good.png') no-repeat;width:36px; height:36px;"></lable></a>&nbsp&nbsp{{place.likedcount}}</td>
                <td>&nbsp&nbsp<a href="{% url 'pages:toshareplace' place.id %}">分享</a>&nbsp&nbsp{{place.sharedcount}}</td>
            </p>

        </div>
    </div>
{% endblock %}

templates/pages/spotdetail.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block style %}
<style>
    #textcontent {
        width: 80%;
        height: auto;
        word-wrap:break-word;
        word-break:break-all;
        overflow: hidden;
        margin:5% auto
    }
</style>
{% endblock %}
{% block topmenucenter %}
    <div style="padding:20px">
        <a id =link_center href="{% url 'pages:home' %}">首页</a>
		<a id =link_center href="{% url 'pages:highsearch' %}">高级筛选</a>
        <a id =link_center  href="{% url 'pages:searchspot' %}">搜索景点</a> 
		<a id =link_center  href="{% url 'pages:retiregroup' %}">养老圈</a> 
    </div>
{% endblock %}
{% block contentbody %}
    <div style="margin: 5% 5%;">
        <div id=textcontent>
                <h4>{{ spot.name }}</h4>
                <img src='{{ MEDIA_URL }}{{ spot.image}}' width="800" height="600" alt=''/>
                <!-- <p align="center">/media/{{ spot.image}}</p> -->
                <p align="left" ><lable>简介:</label> {{ spot.introduce}}</p>
                <p align="left" id=pcontent><lable>附近养老机构:</label>
                    {% for place in spot.nearbyplace.all %}
                    &nbsp&nbsp<a  href="{% url 'pages:placedetail' place.id %}">{{ place.name}}</a>
                    {% endfor %}
                </p>
                <p align="left" id=pcontent><lable>详细地址:</label> {{ spot.address}}</p>
                <p align="left" id=pcontent><lable>开放时间:</label> {{ spot.opentime}}</p>
        </div>
    </div>
{% endblock %}