pages/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name='[pages]'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mgspot/', views.mgspot, name='mgspot'),
    path('addspot/', views.addspot, name='addspot'),
    path('delspot/<spot_id>', views.delspot, name='delspot'),
    path('editspot/<spot_id>', views.editspot, name='editspot'),
    path('mgplace/', views.mgplace, name='mgplace'),
    path('addplace/', views.addplace, name='addplace'),
    path('delplace/<place_id>', views.delplace, name='delplace'),
    path('editplace/<place_id>', views.editplace, name='editplace'),
    path('placedetail/<place_id>', views.placedetail, name='placedetail'),
    path('spotdetail/<spot_id>', views.spotdetail, name='spotdetail'),
    path('mguser/', views.mguser, name='mguser'),
    path('deluser/<user_id>', views.deluser, name='deluser'),
    path('myinfo/', views.myinfo, name='myinfo'),
    path('editmyinfo/', views.editmyinfo, name='editmyinfo'),
    path('home/', views.home, name='home'),
    path('searchplace/', views.searchplace, name='searchplace'),
    path('highsearch/', views.highsearch, name='highsearch'),
    path('retiregroup/', views.retiregroup, name='retiregroup'),
    path('toshareplace/<place_id>', views.toshareplace, name='toshareplace'),
    path('shareplace/<place_id>', views.shareplace, name='shareplace'),
    path('likeplace/<place_id>', views.likeplace, name='likeplace'),
    path('localspot/<place_id>', views.localspot, name='localspot'),
    path('searchspot/', views.searchspot, name='searchspot'),
    path('mginfo_c/', views.mginfo_c, name='mginfo_c'),
    path('editinfo_c/<place_id>', views.editinfo_c, name='editinfo_c'),
    path('magorder_c/', views.mgorder_c, name='mgorder_c'),
    path('makeorder/<place_id><room_kind>', views.makeorder, name='makeorder'),
    path('cancelorder/<order_id>', views.cancelorder, name='cancelorder'),
    path('confirmorder/<order_id>', views.confirmorder, name='confirmorder'),
    path('refuseorder/<order_id>', views.refuseorder, name='refuseorder'),
    path('finishorder/<order_id>', views.finishorder, name='finishorder'),
]

retirementPlaceSys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls', namespace='pages')),
    url(r'^media/(?P<path>.*)', serve, {"document_root":MEDIA_ROOT}),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
     <!-- 使用CSS样式来控制div布局 -->
     <style type="text/css">
        /*定义全局的div布局*/
        div#global{
            /*设置宽度，设置百分比可以根据浏览器自适应宽度*/
            width: 100%;
            /*设置高度，950px是设置是实体高度，不能自适应的*/
            height: 1000px;
            /*设置背景颜色*/
            background-color:white; 
            background-size: cover;
            background-repeat:repeat
        }
        /*定义菜单样式*/
        #topmenucenter{
            width: 80%;
            height: 52px;
            font-size:16px;
            background-color:rgb(177, 207, 228);
            border:0;
            font-weight: bold;
            float:middle;
            vertical-align: middle;
        }
         /*定义右侧菜单样式*/
        #topmenuright{
            width: 20%;
            height: 52px;
            font-size:16px;
            background-color:rgb(177, 207, 228);
            border:0;
            font-weight: bold;
            float:right;
            vertical-align: middle;
        }
        #heading{
            width: 100%;
            height: 32px;
            font-size:32px;
            border:0;
            font-weight: bold;
            float:center;
            vertical-align: bottom;
        }
        #content_body{
            width: 100%;
            height: 900px;
            float: middle;
            font-size:30px;          
        }
        #link{
            font-size:20px;
            padding: 6px;
            text-decoration:none;
            color:gray;          
        }
        #selectedlink{
            font-size:20px;
            padding: 6px;
            text-decoration:none;
            color:black;         
         }
         #link_center{
            font-size:24px;
            padding: 6px;
            text-decoration:none;
            color:gray;          
        }
        #selectedlink_center{
            font-size:24px;
            padding: 6px;
            text-decoration:none;
            color:black;         
         }
        #pcontent{
            font-size:28px;
            color:darkslategrey
        }
    </style>
    {% block style %}
    {% endblock %}
</head>
<style>       
	html,body{text-align:center;margin:auto;}
</style>
<body>
    <!-- 在这里控制全局的页面，定义div的id是"global" -->
    <div id="global">
        <tr>
        <div id="topmenuright" >
                {% block topmenuright %}
                    <a id =link  href="{% url 'pages:myinfo' %}">我的</a> 
                    <a id =link href="{% url 'pages:logout' %}">退出</a> 
                {% endblock %}
            </div>
            <div id="topmenucenter">
                {% block topmenucenter %}
                {% endblock %}
            </div>
        </tr>
        <div id="heading">
            {% block head %}
            {% endblock %}
        </div>
        <div id="content_body">
            <div>
                {% for message in messages %}
                    <div class='alert alert-{{message.tags}}' style="color:coral">{{ message }}</div>
                {% endfor %}
            </div>
                {% block contentbody %}
                {% endblock %}
        </div>
    </div>
</body>
</html>